version: '3.8'

services:
  studio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_URL: ${SUPABASE_URL:-https://supabase-pasteurplus.runflare.run}
      SUPABASE_PUBLIC_ANON_KEY: ${SUPABASE_PUBLIC_ANON_KEY:-placeholder-anon-key}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY:-placeholder-service-role-key}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - meta

  meta:
    build:
      context: .
      dockerfile: Dockerfile.meta
    restart: always
    expose:
      - "8080"
    environment:
      PG_META_PORT: 8080
      DATABASE_URL: ${DATABASE_URL}
