worker_processes 1;
error_log /dev/stderr info;
pid /tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  access_log /dev/stdout;
  server_tokens off;
  client_max_body_size 50m;

  upstream studio_upstream {
    server 127.0.0.1:3000;
  }

  upstream auth_upstream {
    server 127.0.0.1:9999;
  }

  upstream rest_upstream {
    server 127.0.0.1:3001;
  }

  upstream meta_upstream {
    server 127.0.0.1:8080;
  }

  server {
    listen 8000;
    server_name _;

    location = /auth/v1/health {
      proxy_pass http://auth_upstream/health;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /auth/v1/ {
      proxy_pass http://auth_upstream/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header apikey $http_apikey;
      proxy_pass_request_headers on;
    }

    location /rest/v1/ {
      proxy_pass http://rest_upstream/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header apikey $http_apikey;
      proxy_pass_request_headers on;
    }

    location /pg/ {
      proxy_pass http://meta_upstream/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header apikey $http_apikey;
    }

    location / {
      proxy_pass http://studio_upstream;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
}
